# environment = "junction"
environment_image = "empty"
environment       = "./config/scenarios/ClearCircle/environment.yaml"
formation_group   = "./config/scenarios/ClearCircle/formation.ron"

[interaction]
ui-focus-cancels-inputs = true
default-cam-distance    = 150.0

[visualisation.uncertainty]
max-radius = 2.5
scale      = 300.0

[visualisation.height]
objects    = 0.5
height-map = 1.0

[visualisation.draw]
robots                             = true
communication-graph                = false
predicted-trajectories             = false
waypoints                          = false
uncertainty                        = false
paths                              = false
generated-map                      = true
height-map                         = false
sdf                                = false
communication-radius               = false
obstacle-factors                   = false
tracking                           = false
interrobot-factors                 = false
interrobot-factors-safety-distance = false
robot-colliders                    = false
environment-colliders              = false
robot-robot-collisions             = false
robot-environment-collisions       = false

[gbp]
sigma-pose-fixed        = 1e-15
sigma-factor-dynamics   = 1.0
sigma-factor-interrobot = 0.005
sigma-factor-obstacle   = 0.005
sigma-factor-tracking   = 0.1
# iterations-per-timestep = 10
lookahead-multiple = 3
[gbp.iteration-schedule]
internal = 50
external = 20
schedule = 'centered'

[robot]
# planning-horizon = 13.33 # 2r / initial speed
# planning-horizon = 12.4 # 2r / initial speed
planning-horizon = 7
# planning-horizon = 10
# planning-horizon                       = 6.677 # 2r / initial speed
target-speed                           = 10.0
inter-robot-safety-distance-multiplier = 2.5

[robot.radius]
min = 2.0
max = 3.0

[robot.communication]
radius       = 50.0
failure-rate = 0.0

[simulation]
# t0                                        = 0.25
max-time           = 10000.0
time-scale         = 1.0
manual-step-factor = 1
hz                 = 10.0
# world-size                                = 100.0
prng-seed = 31
pause-on-spawn                            = false
despawn-robot-when-final-waypoint-reached = true
exit-application-on-scenario-finished     = true

[rrt]
max-iterations       = 1000000
step-size            = 0.5
collision-radius     = 0.1
neighbourhood-radius = 10.0

# [rrt.smoothing]
# max-iterations = 500
# step-size      = 0.5

[graphviz]
export-location = "./assets/export/"

[graphviz.interrobot.active]
style = "dashed"
len   = 8.0
color = "red"

[graphviz.interrobot.inactive]
style = "dashed"
len   = 8.0
color = "gray"


[manual]
timesteps-per-step = 1
