tiles:
  grid:
  # - '██'
  # - '██'
  - '        '
  - ' ████   '
  - '──███───'
  - '        '
  settings:
    tile-size: 25.0
    path-width: 0.3
    obstacle-height: 2.25
    sdf:
      resolution: 200
      expansion: 0.0
      blur: 0.02
obstacles:
- shape: !polygon
    points:
    - x: 0.0
      y: 0.65
    - x: 1.0
      y: 0.65
    - x: 1.0
      y: 1.0
    - x: 0.0
      y: 1.0
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 2
    col: 2
- shape: !polygon
    points:
    - x: 0.0
      y: 0.65
    - x: 1.0
      y: 0.65
    - x: 1.0
      y: 1.0
    - x: 0.0
      y: 1.0
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 2
    col: 3
- shape: !polygon
    points:
    - x: 0.0
      y: 0.65
    - x: 1.0
      y: 0.65
    - x: 1.0
      y: 1.0
    - x: 0.0
      y: 1.0
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 2
    col: 4

- shape: !polygon
    points:
    - x: 0.0
      y: 0.0
    - x: 0.22573593128807146
      y: 0.0
    - x: 0.5757359312880714
      y: 0.35
    - x: 0.0
      y: 0.35
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 2
    col: 2
- shape: !polygon
    points:
    - x: 0.65
      y: 0.0
    - x: 1.0
      y: 0.0
    - x: 1.0
      y: 0.35
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 2
    col: 2
- shape: !polygon
    points:
    - x: 0.0
      y: 1.0
    - x: 0.22573593128807146
      y: 1.0
    - x: 0.0
      y: 0.77426406871
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 1
    col: 2
- shape: !polygon
    points:
    - x: 0.0
      y: 0.0
    - x: 1.0
      y: 0.0
    - x: 1.0
      y: 1.0
    - x: 0.65
      y: 1.0
    - x: 0.0
      y: 0.35
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 1
    col: 2
- shape: !polygon
    points:
    - x: 1.0
      y: 0.0
    - x: 1.0
      y: 0.35
    - x: 0.65
      y: 0.0
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 1
    col: 1
- shape: !polygon
    points:
    - x: 0.0
      y: 0.0
    - x: 0.0
      y: 1.0
    - x: 1.0
      y: 1.0
    - x: 1.0
      y: 0.77426406871
    - x: 0.22573593128807146
      y: 0.0
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 1
    col: 1

- shape: !polygon
    points:
    - x: 0.0
      y: 0.35
    - x: 1.0
      y: 0.35
    - x: 1.0
      y: 0.0
    - x: 0.0
      y: 0.0
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 2
    col: 3
  
- shape: !polygon
    points:
    - x: 0.0
      y: 0.65
    - x: 1.0
      y: 0.65
    - x: 1.0
      y: 1.0
    - x: 0.0
      y: 1.0
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 2
    col: 4
- shape: !polygon
    points:
    - x: 0.0
      y: 0.65
    - x: 1.0
      y: 0.65
    - x: 1.0
      y: 1.0
    - x: 0.0
      y: 1.0
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 2
    col: 5
- shape: !polygon
    points:
    - x: 0.0
      y: 0.65
    - x: 1.0
      y: 0.65
    - x: 1.0
      y: 1.0
    - x: 0.0
      y: 1.0
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 2
    col: 6
- shape: !polygon
    points:
    - x: 0.0
      y: 0.0
    - x: 0.22573593128807146
      y: 0.0
    - x: 0.5757359312880714
      y: 0.35
    - x: 0.0
      y: 0.35
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 2
    col: 4
- shape: !polygon
    points:
    - x: 0.65
      y: 0.0
    - x: 1.0
      y: 0.0
    - x: 1.0
      y: 0.35
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 2
    col: 4
- shape: !polygon
    points:
    - x: 0.0
      y: 1.0
    - x: 0.22573593128807146
      y: 1.0
    - x: 0.0
      y: 0.77426406871
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 1
    col: 4
- shape: !polygon
    points:
    - x: 0.0
      y: 0.0
    - x: 1.0
      y: 0.0
    - x: 1.0
      y: 1.0
    - x: 0.65
      y: 1.0
    - x: 0.0
      y: 0.35
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 1
    col: 4
- shape: !polygon
    points:
    - x: 1.0
      y: 0.0
    - x: 1.0
      y: 0.35
    - x: 0.65
      y: 0.0
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 1
    col: 3
- shape: !polygon
    points:
    - x: 0.0
      y: 0.0
    - x: 0.0
      y: 1.0
    - x: 1.0
      y: 1.0
    - x: 1.0
      y: 0.77426406871
    - x: 0.22573593128807146
      y: 0.0
  rotation: 0.0
  translation:
    x: 0.0
    y: 0.0
  tile-coordinates:
    row: 1
    col: 3