tiles:
  grid:
  - '        '
  - '   █    '
  - '████████'
  - '        '
  settings:
    tile-size: 25.0
    path-width: 0.5
    obstacle-height: 2.25
    sdf:
      resolution: 200
      expansion: 0.2
      blur: 0.02
obstacles:
- shape: !triangle
    angles:
      A: 1.9
      B: 0.5
    radius: 0.35
  rotation: 0.17
  translation:
    x: 0.0
    y: 0.75
  tile-coordinates:
    row: 1
    col: 3
- shape: !triangle
    angles:
      A: 1.9
      B: 0.5
    radius: 0.475
  rotation: 3.31
  translation:
    x: 0.75
    y: 0.1
  tile-coordinates:
    row: 1
    col: 3
