

factorgraph: {
  variables: {
    belief
    prior
  }
  factors: {
    measurement
    measurement_model: {
        Loss
    }
  }
}

# factorgraph.variables
# factorgraph.factors

# factorgraph.factors.measurements

bevy

