tiles:
  grid:
  - █
  settings:
    tile-size: 200.0
    path-width: 0.1
    obstacle-height: 1.0
    sdf:
      resolution: 500
      expansion: 0.01
      blur: 0.005
  # grid:
  # - █
  # settings:
  #   tile-size: 200.0
  #   path-width: 0.1
  #   obstacle-height: 1.0
  #   sdf:
  #     resolution: 200
  #     expansion: 0.015
  #     blur: 0.01

obstacles:
- shape: !regular-polygon
    sides: 4
    radius: 0.0525
  translation:
    x: 0.625
    y: 0.60125
  rotation: 0.0
  tile-coordinates:
    row: 0
    col: 0
- shape: !regular-polygon
    sides: 4
    radius: 0.035
  translation:
    x: 0.44125
    y: 0.57125
  rotation: 0.0
  tile-coordinates:
    row: 0
    col: 0
- shape: !regular-polygon
    sides: 4
    radius: 0.0225
  translation:
    x: 0.4835
    y: 0.428
  rotation: 0.0
  tile-coordinates:
    row: 0
    col: 0
- shape: !rectangle
    # width: 0.0875
    width: 0.035
    height: 0.0875
    # height: 0.035
  translation:
    x: 0.589
    y: 0.3965
  rotation: 0.0
  tile-coordinates:
    row: 0
    col: 0
- shape: !triangle
    angles:
      A: 1.22
      B: 1.22
    radius: 0.025
  rotation: 0.0
  translation:
    x: 0.5575
    y: 0.5145
  tile-coordinates:
    row: 0
    col: 0
- shape: !triangle
    angles:
      A: 0.6981317007977318
      B: 1.9198621771937625
    radius: 0.01
  rotation: 5.2
  translation:
    x: 0.38
    y: 0.432
  tile-coordinates:
    row: 0
    col: 0

# obstacles:
# - shape: !regular-polygon
#     sides: 4
#     radius: 0.0525
#   translation:
#     x: 0.625
#     y: 0.60125
#   rotation: 0.0
#   tile-coordinates:
#     row: 0
#     col: 0
# - shape: !regular-polygon
#     sides: 4
#     radius: 0.035
#   translation:
#     x: 0.44125
#     y: 0.57125
#   rotation: 0.0
#   tile-coordinates:
#     row: 0
#     col: 0
# - shape: !regular-polygon
#     sides: 4
#     radius: 0.0225
#   translation:
#     x: 0.4835
#     y: 0.428
#   rotation: 0.0
#   tile-coordinates:
#     row: 0
#     col: 0
# - shape: !rectangle
#     width: 0.0875
#     height: 0.035
#   translation:
#     x: 0.589
#     y: 0.3965
#   rotation: 0.0
#   tile-coordinates:
#     row: 0
#     col: 0
# - shape: !triangle
#     angles:
#       A: 0.5235987755982988
#       B: 0.5235987755982988
#     radius: 0.05
#   rotation: 0.0
#   translation:
#     x: 0.5575
#     y: 0.5145
#   tile-coordinates:
#     row: 0
#     col: 0
# - shape: !triangle
#     angles:
#       A: 1.9198621771937625
#       B: 0.6981317007977318
#     radius: 0.03
#   rotation: 5.225
#   translation:
#     x: 0.38
#     y: 0.432
#   tile-coordinates:
#     row: 0
#     col: 0
