tiles:
  grid:
  - '     '
  - ' ███ '
  - ' ███ '
  - ' ███ '  
  - '  │  '
  - ' ███ '
  - ' ███ '
  - ' ███ '
  - '     '
  settings:
    tile-size: 13.0
    path-width: 0.65
    obstacle-height: 2.0
    sdf:
      resolution: 200
      expansion: 0.07
      blur: 0.1
obstacles: []
